export enum AccountType {
  CHECKING = 'CHECKING',
  SAVINGS = 'SAVINGS',
  CREDIT_CARD = 'CREDIT_CARD',
  DEBIT_CARD = 'DEBIT_CARD',
  CASH = 'CASH',
  DIGITAL_WALLET = 'DIGITAL_WALLET',
  INVESTMENT = 'INVESTMENT'
}

export enum Currency {
  DOP = 'DOP',
  USD = 'USD'
}

export enum TransactionType {
  INCOME = 'INCOME',
  EXPENSE = 'EXPENSE',
  TRANSFER = 'TRANSFER',
  CARD_PAYMENT = 'CARD_PAYMENT',
  GOAL_CONTRIBUTION = 'GOAL_CONTRIBUTION',
  GOAL_WITHDRAWAL = 'GOAL_WITHDRAWAL',
  DEBT_PAYMENT = 'DEBT_PAYMENT',
  LOAN_COLLECTION = 'LOAN_COLLECTION',
  ADJUSTMENT = 'ADJUSTMENT'
}

export enum TransactionStatus {
  CONFIRMED = 'CONFIRMED',
  PENDING_REVIEW = 'PENDING_REVIEW',
  VOID = 'VOID'
}

export enum TransactionSource {
  MANUAL = 'MANUAL',
  EMAIL = 'EMAIL',
  SMS = 'SMS',
  IMPORT = 'IMPORT',
  RECURRING = 'RECURRING',
  WEBHOOK = 'WEBHOOK'
}

export enum GoalKind {
  PURCHASE = 'PURCHASE',
  SAVINGS = 'SAVINGS'
}

export enum GoalMode {
  VIRTUAL_ENVELOPE = 'VIRTUAL_ENVELOPE',
  LINKED_ACCOUNT = 'LINKED_ACCOUNT'
}

export enum GoalStatus {
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED'
}

export enum TransportServiceType {
  UBER = 'UBER',
  DIDI = 'DIDI',
  METRO_SANTO_DOMINGO = 'METRO_SANTO_DOMINGO',
  OMSA = 'OMSA',
  PUBLIC_CONCHO = 'PUBLIC_CONCHO',
  TOLL_PASO_RAPIDO = 'TOLL_PASO_RAPIDO',
  FUEL = 'FUEL',
  PARKING = 'PARKING',
  OTHER = 'OTHER'
}

export enum SecureScope {
  VAULT = 'VAULT',
  IDEAS = 'IDEAS'
}

export enum DocumentCategory {
  IDENTITY = 'IDENTITY',
  LEGAL_CONTRACTS = 'LEGAL_CONTRACTS',
  PROPERTY_VEHICLES = 'PROPERTY_VEHICLES',
  FINANCIAL = 'FINANCIAL',
  BUSINESS = 'BUSINESS',
  EDUCATION_WORK = 'EDUCATION_WORK',
  HEALTH = 'HEALTH',
  FAMILY = 'FAMILY',
  PHOTOS_MEMORIES = 'PHOTOS_MEMORIES',
  OTHER = 'OTHER'
}

export enum DocumentStatus {
  ACTIVE = 'ACTIVE',
  EXPIRING_SOON = 'EXPIRING_SOON',
  EXPIRED = 'EXPIRED',
  ARCHIVED = 'ARCHIVED'
}

export enum IdeaType {
  PERSONAL = 'PERSONAL',
  COLLABORATIVE = 'COLLABORATIVE',
  THIRD_PARTY = 'THIRD_PARTY'
}

export enum IdeaStage {
  SEED = 'SEED',
  VALIDATING = 'VALIDATING',
  IN_DEVELOPMENT = 'IN_DEVELOPMENT',
  LAUNCHED = 'LAUNCHED',
  PAUSED = 'PAUSED',
  DISCARDED = 'DISCARDED'
}

export enum LifeArea {
  FINANCIAL_FREEDOM = 'FINANCIAL_FREEDOM',
  CAREER_BUSINESS = 'CAREER_BUSINESS',
  HEALTH_WELLNESS = 'HEALTH_WELLNESS',
  FAMILY_RELATIONSHIPS = 'FAMILY_RELATIONSHIPS',
  PERSONAL_GROWTH = 'PERSONAL_GROWTH',
  LIFESTYLE_TRAVEL = 'LIFESTYLE_TRAVEL'
}

export enum LoanType {
  I_LENT = 'I_LENT',
  I_BORROWED = 'I_BORROWED'
}

export enum QuincenaStatus {
  PLANNED = 'PLANNED',
  RECEIVED = 'RECEIVED',
  CLOSED = 'CLOSED'
}

export enum AllocationCategory {
  FIXED_EXPENSE = 'FIXED_EXPENSE',
  DEBT_CREDIT_CARD = 'DEBT_CREDIT_CARD',
  LIVING_EXPENSES = 'LIVING_EXPENSES',
  SAVINGS_GOALS = 'SAVINGS_GOALS',
  DISCRETIONARY = 'DISCRETIONARY'
}

export enum UniversityExpenseCategory {
  TUITION_FEE = 'TUITION_FEE',
  TRANSPORT = 'TRANSPORT',
  FOOD_SNACKS = 'FOOD_SNACKS',
  MATERIALS_BOOKS = 'MATERIALS_BOOKS',
  WASTE_LEISURE = 'WASTE_LEISURE',
  OTHER = 'OTHER'
}

export enum InventoryCategory {
  CLOTHING = 'CLOTHING',
  FOOTWEAR = 'FOOTWEAR',
  ACCESSORIES = 'ACCESSORIES',
  CONSUMABLES = 'CONSUMABLES',
  TECH_GADGETS = 'TECH_GADGETS',
  HOME_PERSONAL = 'HOME_PERSONAL',
  OTHER = 'OTHER'
}

export enum ItemCondition {
  BRAND_NEW = 'BRAND_NEW',
  EXCELLENT = 'EXCELLENT',
  GOOD = 'GOOD',
  FAIR = 'FAIR',
  DAMAGED = 'DAMAGED',
  UNKNOWN = 'UNKNOWN'
}



